### ISSUE TITLE
Adapter dont start

### ISSUE THREAD

**Issue by ticaki** [iobroker-community-adapters/ioBroker.find-my-iphone-community#16]
Install it first time and get this log msg:
`

  |   |   |  
-- | -- | -- | --
host.tims-pi2 | 2019-12-31 15:15:26.968 | info | Do not restart adapter system.adapter.find-my-iphone.0 because disabled or deleted
host.tims-pi2 | 2019-12-31 15:15:26.968 | error | instance system.adapter.find-my-iphone.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.tims-pi2 | 2019-12-31 15:15:26.968 | error | Caught by controller[0]: at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
host.tims-pi2 | 2019-12-31 15:15:26.967 | error | Caught by controller[0]: at startup (internal/bootstrap/node.js:283:19)
host.tims-pi2 | 2019-12-31 15:15:26.967 | error | Caught by controller[0]: at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
host.tims-pi2 | 2019-12-31 15:15:26.966 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.tims-pi2 | 2019-12-31 15:15:26.966 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.tims-pi2 | 2019-12-31 15:15:26.965 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.tims-pi2 | 2019-12-31 15:15:26.965 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.tims-pi2 | 2019-12-31 15:15:26.965 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.tims-pi2 | 2019-12-31 15:15:26.964 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.find-my-iphone/find-my-iphone.js:15:20)
host.tims-pi2 | 2019-12-31 15:15:26.964 | error | Caught by controller[0]: at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1383:23)
host.tims-pi2 | 2019-12-31 15:15:26.963 | error | Caught by controller[0]: TypeError: fns.adapter is not a function
host.tims-pi2 | 2019-12-31 15:15:26.963 | error | Caught by controller[0]: ^
host.tims-pi2 | 2019-12-31 15:15:26.962 | error | Caught by controller[0]: fns.adapter = fns.adapter(options);
host.tims-pi2 | 2019-12-31 15:15:26.956 | error | Caught by controller[0]: /opt/iobroker/node_modules/soef/soef.js:1383
`

**Comment by Apollon77** [comment]
Try to execute „npm install soef“ in iobroker dir.

**Comment by ticaki** [comment]
Hi,

install it in /opt/ioboker works.

first start ok, but no 2-factor key. Restart adapter get  alot of (see below) and every auto restart a 2 factor key. I stop the adapter.

host.tims-pi1	2020-01-01 13:52:58.414	error	Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:68:7)
host.tims-pi1	2020-01-01 13:52:58.414	error	Caught by controller[0]: at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
host.tims-pi1	2020-01-01 13:52:58.414	error	Caught by controller[0]: at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
host.tims-pi1	2020-01-01 13:52:58.414	error	Caught by controller[0]: at (anonymous function).(anonymous function)._0x5c1e98 (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:76202)
host.tims-pi1	2020-01-01 13:52:58.413	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.find-my-iphone/node_modules/soef/soef.js:609:26
host.tims-pi1	2020-01-01 13:52:58.413	error	Caught by controller[0]: at Devices.setState (/opt/iobroker/node_modules/iobroker.find-my-iphone/node_modules/soef/soef.js:642:36)
host.tims-pi1	2020-01-01 13:52:58.412	error	Caught by controller[0]: TypeError: Cannot read property 'val' of undefined
find-my-iphone.0	2020-01-01 13:52:57.894	info	(25104) Terminated (NO_ERROR): Without reason
find-my-iphone.0	2020-01-01 13:52:57.892	info	(25104) terminating
find-my-iphone.0	2020-01-01 13:52:57.886	error	(25104) TypeError: Cannot read property 'val' of undefined at Devices.setState (/opt/iobroker/node_modules/iobroker.find-my-iphone/node_modules/soef/soef.js:642:36) at /opt/iobroker/node_modul
find-my-iphone.0	2020-01-01 13:52:57.883	error	(25104) uncaught exception: Cannot read property 'val' of undefined
find-my-iphone.0	2020-01-01 13:52:57.875	silly	(25104) Objects redis pmessage find-my-iphone.0.*/cfg.o.find-my-iphone.0.Tims-iMac.lost:{"type":"state","common":{"name":"Lost Mode","type":"string","role":"state","desc":"Parameter: usertext[;phone n
find-my-iphone.0	2020-01-01 13:52:57.864	silly	(25104) Objects redis pmessage find-my-iphone.0.*/cfg.o.find-my-iphone.0.Tims-iMac:{"type":"device","common":{"name":"Tims-iMac","type":"string","role":"device"},"native":{"id":"huvLQyne1thtzHXVLxV+WV
find-my-iphone.0	2020-01-01 13:52:56.205	silly	(25104) redis psubscribe cfg.o.find-my-iphone.0.*
find-my-iphone.0	2020-01-01 13:52:56.154	silly	(25104) States redis pmessage system.adapter.find-my-iphone.0.logLevel/system.adapter.find-my-iphone.0.logLevel:{"val":"silly","ack":true,"ts":1577883176126,"q":0,"from":"system.adapter.find-my-iphone
find-my-iphone.0	2020-01-01 13:52:56.108	debug	(25104) Schedule restart: 0 3 * * *
find-my-iphone.0	2020-01-01 13:52:56.007	info	(25104) starting. Version 0.2.17 in /opt/iobroker/node_modules/iobroker.find-my-iphone, node: v10.18.0
host.tims-pi1	2020-01-01 13:52:54.079	info	instance system.adapter.find-my-iphone.0 started with pid 25104
host.tims-pi1	2020-01-01 13:52:53.041	info	Restart adapter system.adapter.find-my-iphone.0 because enabled
host.tims-pi1	2020-01-01 13:52:53.041	info	instance system.adapter.find-my-iphone.0 terminated with code 0 (NO_ERROR)

then put the last 2 factor key into password field and then:
find-my-iphone.0	2020-01-01 13:54:03.765	silly	(26009) redis psubscribe cfg.o.find-my-iphone.0.*
find-my-iphone.0	2020-01-01 13:54:03.702	silly	(26009) States redis pmessage system.adapter.find-my-iphone.0.logLevel/system.adapter.find-my-iphone.0.logLevel:{"val":"silly","ack":true,"ts":1577883243684,"q":0,"from":"system.adapter.find-my-iphone
find-my-iphone.0	2020-01-01 13:54:03.666	debug	(26009) Schedule restart: 0 3 * * *
find-my-iphone.0	2020-01-01 13:54:03.571	info	(26009) starting. Version 0.2.17 in /opt/iobroker/node_modules/iobroker.find-my-iphone, node: v10.18.0
host.tims-pi1	2020-01-01 13:54:01.530	info	instance system.adapter.find-my-iphone.0 started with pid 26009
host.tims-pi1	2020-01-01 13:54:01.512	info	"system.adapter.find-my-iphone.0" enabled
host.tims-pi1	2020-01-01 13:53:06.002	info	instance system.adapter.find-my-iphone.0 terminated with code null ()
host.tims-pi1	2020-01-01 13:53:06.002	warn	instance system.adapter.find-my-iphone.0 terminated due to SIGTERM

But i only see my old iMac there with High Sierra. I have 7 devices in my account.

Gruß Tim

> Am 31.12.2019 um 18:53 schrieb Ingo Fischer <notifications@github.com>:
> 
> npm install soef

**Comment by ticaki** [comment]
Keine Ahnung wieso, aber gerade nochmal probiert und es geht
